
services:

  # ─────────────────────────────────────────
  # Zookeeper (requis par Confluent Kafka)
  # ─────────────────────────────────────────
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: notif-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  # ─────────────────────────────────────────
  # Kafka 7.6.0
  # ─────────────────────────────────────────
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: notif-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 15s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  # ─────────────────────────────────────────
  # Kafka Init — crée les topics
  # ─────────────────────────────────────────
  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    container_name: notif-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic raw-notifications --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notifications-sms --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notifications-email --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notifications-push --partitions 1 --replication-factor 1
        echo 'Topics créés avec succès.'
      "
    restart: on-failure
